version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: powerfit-mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: powerfit
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: mahmoudzhiri03/springboot-backend:latest
    container_name: pi-backend
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/powerfit
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

volumes:
  mysql_data: